version: '{build}'

branches:
  only:
    - master
    - /pull\/.+\/merge/

image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: false

configuration:
  - Release

before_build:
  - cmd: nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
  - cmd: git remote set-url origin https://github.com/baunegaard/expressioncache.git

build_script:
  - ps: .\build.ps1

test: off

deploy: off
