version: '{build}'

branches:
  only:
    - master
    - /pull\/.+\/merge/

image: Visual Studio 2017

environment:
  MYGET_API_KEY:
    secure: 78qy8e6pKfJlQV7RAG5tJOWegzXpjASkUs3aFdVBoPYA5gi6+mWdjbuAmNa5OQPe

assembly_info:
  patch: false

configuration:
  - Release

build_script:
  - ps: .\build.ps1

test: off

after_test:
 - "SET PATH=C:\\Python36;C:\\Python36\\Scripts;%PATH%"
 - pip install codecov
 - codecov -f "coverage.xml"

deploy: off
