version: '{build}'

branches:
  only:
    - master
    - /pull\/.+\/merge/

image: Visual Studio 2017

environment:
  CODECOV_TOKEN:
    secure: I7bieXWtobeo2d40BMek/GSjy5Z0Wihr1dZ+G8qujzKpGyzxxaR7zzPrWteRfkSK
  MYGET_API_KEY:
    secure: 78qy8e6pKfJlQV7RAG5tJOWegzXpjASkUs3aFdVBoPYA5gi6+mWdjbuAmNa5OQPe

assembly_info:
  patch: false

configuration:
  - Release

before_build:
  - cmd: git remote set-url origin https://github.com/Baune8D/expressioncache.git

build_script:
  - ps: .\build.ps1

test: off

deploy: off
