version: '{build}'

branches:
  only:
    - master
    - /pull\/.+\/merge/

skip_tags: true

image: Visual Studio 2017

environment:
  GITVERSION_REMOTE_USERNAME: baunegaard
  GITVERSION_REMOTE_PASSWORD:
    secure: I3rxSgF7ui96WUsoZVO2Yg==

assembly_info:
  patch: false

configuration:
  - Release

before_build:
  - cmd: nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
  - cmd: git remote set-url origin https://github.com/baunegaard/expressioncache.git

build_script:
  - ps: .\build.ps1

test: off
